name: CI main

env:
  API_KEY: ${{ secrets.API_KEY }}
  API_SECRET: ${{ secrets.API_SECRET }}
  API_URL: ${{ secrets.API_URL }}

on:
  push:
    branches:
      - main

jobs:

  run-validations:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Run mypy
      run: poetry run mypy . --ignore-missing-imports
    - name: Run unit tests
      run: |
        poetry run pytest -m "not integ"
    - name: Run integration tests
      run: |
        poetry run pytest -m "integ"